version: "3"
services:
  database:
    image: mysql/mysql-server:5.7
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/mysql
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    networks:
      - mynetwork
   
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: "directus_dan"
      MYSQL_USER: "daniel"
      MYSQL_PASSWORD: "abc"
      # POSTGRES_USER: "directus"
      # POSTGRES_PASSWORD: "directus"
      # POSTGRES_DB: "directus"

  cache:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  directus:
    image: directus/directus:10.8.2
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    networks:
      - mynetwork
   
    depends_on:
      - cache
      - database
    environment:
      KEY: "random_key"
      SECRET: "random_secret"

      DB_CLIENT: "mysql"
      DB_HOST: "database"
      DB_PORT: "3306"
      DB_DATABASE: "directus_dan"
      DB_USER: "daniel"
      DB_PASSWORD: "abc"

      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379/0"

      ADMIN_EMAIL: "admin@test.de"
      ADMIN_PASSWORD: "123"
      CORS_ENABLED: true
networks:
  mynetwork:




      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: "https://directus.example.com"